### ISSUE TITLE
Lien vers zoom "région centre" (liste des régions)

### ISSUE THREAD

**Issue by Cyrille37** [Artefacts-coop/ArchipelOCentre#4]
Dans la liste des régions la zone générale est nommée "--" ce qui n'est pas explicite. J'ai cherché comment revenir au zoom large.

**Comment by RomainLalande** [comment]
Les "--" équivalaient à la zone "Région".
J'ai renommé en "Région Centre" pour que ce soit plus lisible.

**Comment by Cyrille37** [comment]
Merci c'est impec :100:
